# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Step Aument
email: saument@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Compassionate Coder. Technical Leader.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.stephenaument.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: saument
github_username:  stephenaument
rss: feed.xml
permalink: /blog/:title/

wpm: 225

google_analytics: true
google_analytics_tracking_id: UA-126696590-1

disqus:
  shortname: www-stephenaument-com

author:
  name: Step Aument
  twitter: saument
  linkedin: stephenaument
  github: stephenaument

convertkit:
  form_uid: 697093712f
  form_url: https://f.convertkit.com/697093712f/34b641aedd.js

# Build settings
markdown: kramdown
plugins:
  - jekyll-assets
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  load_paths:
    - node_modules

assets:
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  compress:
    css: sass
    js: uglifier
  sources:
    - _assets/css
    - _assets/images
    - _assets/javascript

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
